#!/bin/bash

if [ "$#" -ne 1 ]; then
	echo "Expected a spectre file generated by the shadow compiler!";
	exit 1;
fi

FILE_PATH=`realpath $1`
FILE_NAME=`basename $FILE_PATH`
FILE_NAME_NO_EXT="${FILE_NAME%.*}"
ASM_FILE="$FILE_NAME_NO_EXT.s"
OBJ_FILE="$FILE_NAME_NO_EXT.o"
EXEC_FILE="$FILE_NAME_NO_EXT"

spectre $1
as -mfloat-abi=hard -mfpu=vfp $ASM_FILE -o $OBJ_FILE
ld $OBJ_FILE -o $EXEC_FILE --whole-archive -L/usr/include/libspectre -l:libspectre.a --whole-archive -L/home/artoria/shadow/rt_build -l:shadow_rt.a
rm -f $ASM_FILE $OBJ_FILE
